In [5]:
#Import the numpy package under the name `np` 
import numpy as np

In [6]:
#Create a null vector of size 10
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
#Create a null vector of size 10 but the fifth value which is 1 
b = np.zeros(10)
b[4]=1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [8]:
#Create a vector with values ranging from 10 to 49 
c = np.arange(10,50)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
#Create a 3x3 matrix with values ranging from 0 to 8
d = np.arange(0, 9).reshape(3,3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
e = np.array([1,2,0,0,4,0])
np.nonzero(e)
#e[e != 0]

(array([0, 1, 4]),)

In [11]:
#Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
#Create a 3x3x3 array with random values
f = np.random.random((3,3,3))
f

array([[[0.66401767, 0.56326664, 0.53696638],
        [0.38315284, 0.17986806, 0.11234031],
        [0.68909346, 0.21645088, 0.11413687]],

       [[0.40171151, 0.56196671, 0.0979667 ],
        [0.44113669, 0.00381044, 0.0306991 ],
        [0.69037814, 0.46027063, 0.85071754]],

       [[0.68786975, 0.34728137, 0.50936984],
        [0.19217789, 0.40628113, 0.36651431],
        [0.12871491, 0.95183213, 0.72247967]]])

In [13]:
#Create a 10x10 array with random values and find the minimum and maximum values
g = np.random.random((10,10))
gmin, gmax = g.min(), g.max()
print(g)
print("The minimum value is", gmin, "The maximum value is", gmax)

[[0.63028973 0.29583816 0.25113078 0.08002885 0.07232743 0.33358555
  0.4059295  0.66470013 0.08370456 0.04725013]
 [0.35387702 0.505861   0.67455904 0.31315062 0.85637415 0.95802819
  0.48565015 0.16430856 0.92504483 0.00927057]
 [0.40828833 0.31095486 0.16455878 0.20852918 0.93929694 0.3839145
  0.62903823 0.97540411 0.14811548 0.04504074]
 [0.31789561 0.44790655 0.17290299 0.90259024 0.49878966 0.53422542
  0.98538211 0.54239783 0.52693431 0.60998153]
 [0.67452163 0.64307999 0.51865751 0.81793034 0.13195588 0.36645589
  0.86218144 0.00803981 0.33123596 0.74470037]
 [0.80806684 0.83911735 0.20285356 0.93221869 0.139806   0.17590963
  0.20684135 0.56433331 0.10219133 0.15673985]
 [0.94797644 0.70076941 0.29654911 0.94142058 0.74689765 0.65067449
  0.15380888 0.80338115 0.31093323 0.67655698]
 [0.35297405 0.78095941 0.33946112 0.62991628 0.12909547 0.39205253
  0.37524855 0.54271316 0.89789635 0.49399804]
 [0.16256858 0.48663255 0.04863399 0.15995412 0.61921176 0.59999136
  0.09850424 

In [14]:
#Create a random vector of size 30 and find the mean value
h = np.random.random(30)
h

array([0.22613444, 0.01809818, 0.38842176, 0.05312684, 0.5026804 ,
       0.93715067, 0.14939537, 0.22931434, 0.59338588, 0.68786081,
       0.9758779 , 0.83867113, 0.46778421, 0.49564896, 0.73442589,
       0.11423   , 0.29431389, 0.58248234, 0.07770072, 0.22470048,
       0.15218202, 0.83343222, 0.80047168, 0.29013173, 0.79397143,
       0.40539521, 0.01358536, 0.35056777, 0.13194876, 0.92754255])

In [15]:
np.mean(h)

0.44302109800219236

In [18]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
np.diagflat([1,2,3,4],-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [20]:
#Normalize a 5x5 random matrix

h= np.random.random((5,5))
print("Original Array:")
print(h)

Original Array:
[[0.29789821 0.30886228 0.41047049 0.93111192 0.01470279]
 [0.25238951 0.68469783 0.70980494 0.57475844 0.93552442]
 [0.21199825 0.12592029 0.90946892 0.34307636 0.38781965]
 [0.76131303 0.55034129 0.62270412 0.05853535 0.11614361]
 [0.0934581  0.8607986  0.42064526 0.34599417 0.27647723]]


In [21]:
hmax, hmin = h.max(), h.min()
h = (h - hmin)/(hmax - hmin)
print("After normalization:")
print(h)

After normalization:
[[0.30754644 0.31945328 0.42979843 0.99520808 0.        ]
 [0.2581246  0.72760567 0.75487165 0.60821296 1.        ]
 [0.21426023 0.12078072 0.97170408 0.35660931 0.40519993]
 [0.81080876 0.58169626 0.66028133 0.04760157 0.11016337]
 [0.08552722 0.91884876 0.44084811 0.35977801 0.28428355]]


In [22]:
#How to find common values between two arrays?
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


In [23]:
#Create a random vector of size 10 and sort it
z= np.random.random(10)
z

array([0.72070585, 0.9534013 , 0.16238893, 0.24823014, 0.62204528,
       0.76127873, 0.53441618, 0.20836553, 0.74184685, 0.08003975])

In [24]:
sort(z)

NameError: name 'sort' is not defined